#!/bin/bash
# ============================================================================
# MesonGS Plus 单场景 Prune + 单点 Size-limited Eval
#
# 面向最终用户：只需要两个输入即可工作
#   1. SOURCE_PATH     —— COLMAP/NeRF 格式场景目录 (内含 images/ sparse/...)
#   2. INIT_CHECKPOINT —— 一个预训练好的 3DGS .ply (来自 3DGS 官方训练流程)
#
# 无需任何 scene/dataset 名字，也不需要 YAML 配置文件，
# 剪枝率 / 目标码率 / 超参全部通过环境变量传入。
#
# Pipeline：
#   Step 1  对 PRUNING_RATES 每个 rate 做一次剪枝 + 量化，保存 ckpt
#   Step 2  用 SIZE_LIMIT_MB 作目标，对每个 ckpt 各做一次 encode-decode，
#           打印 PSNR / SSIM / LPIPS 对比表
#
# 运行示例：
#   # 最简：用默认参数 (pruning_rates=[0.2, 0.4], size=20 MB)
#   SOURCE_PATH=/data/360/counter \
#   INIT_CHECKPOINT=/data/360_3dgs/counter/point_cloud.ply \
#       bash scripts/compress_single_scene.sh
#
#   # 自定义
#   SOURCE_PATH=/data/tandt/truck \
#   INIT_CHECKPOINT=/data/tandt_3dgs/truck/point_cloud.ply \
#   PRUNING_RATES="0.0 0.2 0.4" \
#   SIZE_LIMIT_MB=25 \
#   OUTPUT_ROOT=./my_runs/truck \
#       bash scripts/compress_single_scene.sh
#
#   # 已剪枝过，只做评估
#   SKIP_PRUNE=1 SOURCE_PATH=... INIT_CHECKPOINT=... \
#       bash scripts/compress_single_scene.sh
# ============================================================================

set -e

eval "$(conda shell.bash hook)"
conda activate compressgs

# =============== 场景和预训练3DGS权重（可由同名环境变量覆盖）===============
SOURCE_PATH=${SOURCE_PATH:-/mnt/storage/users/szxie_data/nerf_data/360_v2/counter}
INIT_CHECKPOINT=${INIT_CHECKPOINT:-/mnt/storage/users/szxie_data/MesonGS/outputs/360_v2/counter/baseline/3dgs/point_cloud/iteration_30000/point_cloud.ply}

[ -d "$SOURCE_PATH" ]     || { echo "ERROR: SOURCE_PATH 不是目录: $SOURCE_PATH"; exit 1; }
[ -f "$INIT_CHECKPOINT" ] || { echo "ERROR: INIT_CHECKPOINT 不存在: $INIT_CHECKPOINT"; exit 1; }

# =============== 可选输入 ===============
PRUNING_RATES=${PRUNING_RATES:-"0.2 0.4"}    # 空格分隔的剪枝率列表
SIZE_LIMIT_MB=${SIZE_LIMIT_MB:-20}           # 单点目标码率上限 (MB)
CUDA_DEVICE=${CUDA_DEVICE:-0}                # GPU id
IMAGES=${IMAGES:-images}                     # COLMAP images 子目录
OUTPUT_ROOT=${OUTPUT_ROOT:-outputs_single}   # 所有产物根目录
TAG=${TAG:-$(basename "$SOURCE_PATH")}       # 用于输出子目录命名，默认取场景路径 basename
SKIP_PRUNE=${SKIP_PRUNE:-${SKIP_TRAIN:-0}}  # =1 跳过剪枝 (SKIP_TRAIN 为旧兼容名)

# =============== MesonGS Plus 超参（默认值即 SOTA 配置）===============
N_BLOCK=${N_BLOCK:-80}
CODEBOOK_SIZE=${CODEBOOK_SIZE:-4096}
NUM_BITS=${NUM_BITS:-16}
RAHT=${RAHT:-True}
USE_INDEXED=${USE_INDEXED:-True}
SH_KEEP_THRESHOLD=${SH_KEEP_THRESHOLD:--1}
SH_KEEP_TOPK=${SH_KEEP_TOPK:-1000000}
OCTREE_DEPTH=${OCTREE_DEPTH:-19}             # 八叉树深度（默认 19，与 SOTA 场景一致）
PRUNING_RATE_PLACEHOLDER=-1.0 

# =============== TMC3 （MPEG G-PCC 二进制，编码器依赖）===============
TMC3_PATH=${TMC3_PATH:-/home/gejunchen/Work/2026-1/Projects/compressgs_autotune/mpeg-pcc-tmc13/build/tmc3/tmc3}
if [ ! -x "$TMC3_PATH" ]; then
    echo "WARNING: TMC3_PATH 不存在或不可执行: $TMC3_PATH"
    echo "         请设置 TMC3_PATH 指向已编译好的 tmc3 二进制。"
fi
export TMC3_PATH

TRAIN_DIR_TMPL="$OUTPUT_ROOT/${TAG}_train_nb${N_BLOCK}_bits${NUM_BITS}_prune{percent}_cb${CODEBOOK_SIZE}_topk${SH_KEEP_TOPK}_raht${RAHT}_use_indexed${USE_INDEXED}"

mkdir -p "$OUTPUT_ROOT"
MIN_YAML="$OUTPUT_ROOT/${TAG}_config.yaml"
cat > "$MIN_YAML" <<YAML
# Auto-generated by scripts/compress_single_scene.sh
n_block: $N_BLOCK
cb: $CODEBOOK_SIZE
depth: $OCTREE_DEPTH
prune: 0.4
finetune_lr_scale: 0.1
YAML
echo "Generated minimal config: $MIN_YAML"

echo "=========================================="
echo "MesonGS Plus 单场景 Prune + 单点 Eval"
echo "  source_path    : $SOURCE_PATH"
echo "  init_checkpoint: $INIT_CHECKPOINT"
echo "  pruning_rates  : $PRUNING_RATES"
echo "  size_limit_mb  : $SIZE_LIMIT_MB"
echo "  output_root    : $OUTPUT_ROOT"
echo "  tag            : $TAG"
echo "  CUDA device    : $CUDA_DEVICE"
echo "=========================================="


if [ "$SKIP_PRUNE" != "1" ]; then
    echo ""
    echo "------------------------------------------"
    echo "[Step 1/2] Pruning (pruning_rates=$PRUNING_RATES)"
    echo "------------------------------------------"

    PYTHONPATH=$PYTHONPATH:$(pwd) CUDA_VISIBLE_DEVICES=$CUDA_DEVICE python splatwizard/scripts/train_multi_prune.py \
        --source_path "$SOURCE_PATH" \
        --yaml_path "$MIN_YAML" \
        --model mesongs_plus \
        --optim mesongs_plus \
        --force_setup \
        --iterations 1 \
        --checkpoint_iterations 199 399 599 1999 2999 3999 4999 5999 6999 7999 \
        --checkpoint_type pth \
        --final_checkpoint pth \
        --scene_imp "$TAG" \
        --images "$IMAGES" \
        --use_quat \
        --eval_freq 1 \
        --n_block $N_BLOCK \
        --codebook_size $CODEBOOK_SIZE \
        --num_bits $NUM_BITS \
        --raht $RAHT \
        --use_indexed $USE_INDEXED \
        --sh_keep_threshold $SH_KEEP_THRESHOLD \
        --sh_keep_topk $SH_KEEP_TOPK \
        --init_checkpoint "$INIT_CHECKPOINT" \
        --pruning_rates_list $PRUNING_RATES \
        --output_dir_template "$TRAIN_DIR_TMPL"
fi

SUMMARY_FILE=$(mktemp)
echo "prune_rate, size_mb, psnr, ssim, lpips, output_dir" > "$SUMMARY_FILE"

for PR in $PRUNING_RATES; do
    TRAIN_DIR="${TRAIN_DIR_TMPL/\{percent\}/$PR}"
    CHECKPOINT="$TRAIN_DIR/checkpoints/ckpt1.pth"
    EVAL_DIR="$OUTPUT_ROOT/${TAG}_eval_nb${N_BLOCK}_bits${NUM_BITS}_prune${PR}_sz${SIZE_LIMIT_MB}MB_cb${CODEBOOK_SIZE}_topk${SH_KEEP_TOPK}"

    if [ ! -f "$CHECKPOINT" ]; then
        echo "  [prune=$PR] checkpoint 不存在，跳过: $CHECKPOINT"
        echo "$PR, , , , , (missing checkpoint)" >> "$SUMMARY_FILE"
        continue
    fi

    echo ""
    echo "  >>> prune=$PR  size_limit=${SIZE_LIMIT_MB}MB"
    echo "      checkpoint: $CHECKPOINT"
    echo "      output    : $EVAL_DIR"

    PYTHONPATH=$PYTHONPATH:$(pwd) CUDA_VISIBLE_DEVICES=$CUDA_DEVICE python splatwizard/scripts/eval.py \
        --source_path "$SOURCE_PATH" \
        --output_dir "$EVAL_DIR" \
        --yaml_path "$MIN_YAML" \
        --model mesongs_plus \
        --optim mesongs_plus \
        --eval_mode ENCODE_DECODE \
        --checkpoint "$CHECKPOINT" \
        --force_setup \
        --scene_imp "$TAG" \
        --images "$IMAGES" \
        --use_quat False \
        --size_limit_mb "$SIZE_LIMIT_MB" \
        --n_block $N_BLOCK \
        --num_bits $NUM_BITS \
        --percent "$PR" \
        --codebook_size $CODEBOOK_SIZE \
        --raht $RAHT \
        --use_indexed $USE_INDEXED \
        --sh_keep_threshold $SH_KEEP_THRESHOLD \
        --sh_keep_topk $SH_KEEP_TOPK \
        --pruning_rate $PRUNING_RATE_PLACEHOLDER \
        --save_bitstream \
        --save_rendered_image

    # 从 results.json 抽取关键指标
    RJ="$EVAL_DIR/results.json"
    if [ -f "$RJ" ]; then
        LINE=$(python -c "
import json, pathlib
d = json.loads(pathlib.Path('$RJ').read_text())
print(f\"{d.get('total_bytes', 0)/1048576:.4f}, {d.get('PSNR', float('nan')):.4f}, {d.get('SSIM', float('nan')):.6f}, {d.get('LPIPS', float('nan')):.6f}\")
")
        echo "$PR, $LINE, $EVAL_DIR" >> "$SUMMARY_FILE"
    else
        echo "$PR, , , , , (no results.json)" >> "$SUMMARY_FILE"
    fi
done

